### ISSUE TITLE
How to create my own template ?

### ISSUE THREAD

**Issue by darkprogrammer21321** [yaras6/bs5-intro-tour#2]
hello :D ! i tried using the code below to customize my template but it's not working .. any idea how i can customize template design with bs5-intro-tour?

![image](https://user-images.githubusercontent.com/110042408/181026353-3101f30b-d503-48f9-b25c-28e92021da4a.png)

**Comment by yaras6** [comment]
Currently there is no way to extend temple, you can override translations only by providing translations object. If overriding translations is not enough, I will try to extend the pług in soon

**Comment by darkprogrammer21321** [comment]
Aww i seee .. will be great if you could extend the plug in on this :D .. thanks man .. the list of API translations object will be the same with the bootstrap tour right ?

**Comment by yaras6** [comment]
Have you checked index.html file? There is an example, where you can see how to override translations.

I refreshed my memory and there is already possibility to put own popover settings as well. Below you can take a look on an example. You can override all popover settings available in BS5

`
    var tour = new Tour(steps, {
            translations: {
                next: "Dalej",
                previous: "Wróć",
                finish: "Zakończ"
            },
            popover: {
                template:  '<div id="tour" class="popover popover-tour" role="tooltip">' +
            '<div class="popover-arrow"></div>' +
            '<div class="tour-exit"></div>' +
            '<h3 class="popover-header"></h3>' +
            '<div class="popover-body">' +
            '</div>' +
            '<div class="popover-footer">' +
            '   <a class="btn tour-prev">' +
            'Wstecz' +
            '   </a>' +
            '   <a class="btn tour-next">' +
            'Dalej' +
            '   </a>' +
            '   <a class="btn btn-primary tour-finish hidden">' +
            'Koniec' +
            '   </a>' +
            '</div>' +
            '</div>'
            }
        });`

PS. Feel free to put own translations or overriding template.
